// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orbit.Mobile.Data;

#nullable disable

namespace Orbit.Mobile.Data.Migrations
{
    [DbContext(typeof(OrbitLocalDbContext))]
    partial class OrbitLocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Orbit.Mobile.Data.LocalCalendarEvent", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CopiedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CopyBaseLines")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CopyBaseTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CopyOfLocalId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKeptCopy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSharedWithOthers")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSyncedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocalId");

                    b.HasIndex("ServerId")
                        .IsUnique()
                        .HasFilter("\"ServerId\" IS NOT NULL");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("Orbit.Mobile.Data.LocalChatGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Members")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatGroups");
                });

            modelBuilder.Entity("Orbit.Mobile.Data.LocalChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CiphertextBase64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupMessageId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsReadByEveryone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NonceBase64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OtherUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SentAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "SentAtUtc");

                    b.HasIndex("OtherUserId", "SentAtUtc");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Orbit.Mobile.Data.LocalContact", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPendingApprovalFromOtherParty")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastMessageAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PresenceStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKeyBase64")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresApprovalFromCurrentUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Orbit.Mobile.Data.LocalNote", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CopiedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CopyBaseLines")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CopyBaseTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CopyOfLocalId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedCiphertext")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedNonce")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKeptCopy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSharedWithOthers")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSyncedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocalId");

                    b.HasIndex("ServerId")
                        .IsUnique()
                        .HasFilter("\"ServerId\" IS NOT NULL");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Orbit.Mobile.Data.LocalNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyArgumentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRaisedHere")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleArgumentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Orbit.Mobile.Data.LocalPermission", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Orbit.Mobile.Data.LocalStoreOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StoreOwners");
                });

            modelBuilder.Entity("Orbit.Mobile.Data.LocalTaskList", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CopiedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CopyBaseLines")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CopyBaseTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CopyOfLocalId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedCiphertext")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedNonce")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsKeptCopy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSharedWithOthers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSyncedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LinkedWarehouseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocalId");

                    b.HasIndex("ServerId")
                        .IsUnique()
                        .HasFilter("\"ServerId\" IS NOT NULL");

                    b.ToTable("TaskLists");
                });

            modelBuilder.Entity("Orbit.Mobile.Data.LocalWarehouse", b =>
                {
                    b.Property<Guid>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CopiedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CopyBaseLines")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CopyBaseTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CopyOfLocalId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedCiphertext")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedNonce")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKeptCopy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSharedWithOthers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSyncedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocalId");

                    b.HasIndex("ServerId")
                        .IsUnique()
                        .HasFilter("\"ServerId\" IS NOT NULL");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("Orbit.Mobile.Data.OutboxEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QueuedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "Id");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("Orbit.Mobile.Data.OutgoingChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<long>("QueuedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RecipientUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("OutgoingChatMessages");
                });

            modelBuilder.Entity("Orbit.Mobile.Data.PendingCalendarLink", b =>
                {
                    b.Property<Guid>("CalendarEventLocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskListLocalId")
                        .HasColumnType("TEXT");

                    b.HasKey("CalendarEventLocalId");

                    b.ToTable("PendingCalendarLinks");
                });

            modelBuilder.Entity("Orbit.Mobile.Data.SyncCursor", b =>
                {
                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntityType");

                    b.ToTable("SyncCursors");
                });
#pragma warning restore 612, 618
        }
    }
}
