using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Orbit.Contracts.Users;

namespace Orbit.Mobile.Crypto;

/// <summary>
/// The user's Orbit chat key pair, and everything done with it: agreeing a key with someone else,
/// sealing and opening messages, and wrapping the private key for backup.
///
/// This must interoperate byte-for-byte with ciphertext produced by browsers, in both directions,
/// against the same stored keys. The spec is fixed by Orbit.Web's <c>wwwroot/js/e2eeChat.js</c> and
/// cannot be renegotiated without breaking every existing conversation - see info/orbit-maui-plan.md
/// §4.1, and the vectors in tests/Orbit.Mobile.Tests/Crypto, which were generated by a real browser
/// running that file.
///
/// <b>The message key is the raw ECDH shared secret, used directly as the AES key. There is no KDF.</b>
/// WebCrypto's <c>deriveKey(ECDH → AES-GCM, 256)</c> does exactly that, and in .NET the matching call is
/// <see cref="ECDiffieHellman.DeriveRawSecretAgreement"/>. Every other Derive* overload
/// (<c>DeriveKeyFromHash</c>, <c>DeriveKeyFromHmac</c>) applies a KDF and is wrong here - and wrong in
/// the worst way, producing code that encrypts and decrypts happily against itself while being unable
/// to read a single message from the web client.
/// </summary>
public sealed class ChatIdentity : IDisposable
{
    /// <summary>WebCrypto appends the tag to the ciphertext; .NET keeps it separate. See <see cref="EncryptedText"/>.</summary>
    private const int TagSizeBytes = 16;

    private const int NonceSizeBytes = 12;

    /// <summary>The uncompressed EC point marker: a raw public key is 0x04 ‖ X ‖ Y, 65 bytes for P-256.</summary>
    private const byte UncompressedPointMarker = 0x04;

    private const int CoordinateSizeBytes = 32;

    /// <summary>
    /// OWASP's current minimum for PBKDF2-HMAC-SHA256, and what the browser uses. Stored with each
    /// backup rather than assumed at restore time, so raising it later doesn't invalidate old backups.
    /// </summary>
    private const int Pbkdf2IterationCount = 600_000;

    private readonly ECDiffieHellman _keyPair;

    private ChatIdentity(ECDiffieHellman keyPair) => _keyPair = keyPair;

    /// <summary>Generates a new identity - what a user with no backup to restore gets.</summary>
    public static ChatIdentity Create() => new(ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256));

    public static ChatIdentity FromPrivateKeyJwk(string json)
    {
        var jwk = JsonSerializer.Deserialize<JsonWebKey>(json)
            ?? throw new CryptographicException("The private key backup was empty.");

        return new ChatIdentity(ECDiffieHellman.Create(jwk.ToPrivateKeyParameters()));
    }

    /// <summary>
    /// Null when the password is wrong or the backup is damaged, rather than throwing - the caller
    /// cannot tell those apart either, and both mean the same thing: this key cannot be recovered.
    /// Matches what the browser's restoreOwnPrivateKeyFromBackup does.
    /// </summary>
    public static ChatIdentity? FromBackup(WrappedPrivateKeyDto backup, string password)
    {
        try
        {
            var wrappingKey = DeriveWrappingKey(password, Convert.FromBase64String(backup.SaltBase64), backup.Iterations);
            var json = OpenSealed(
                wrappingKey, new EncryptedText(backup.CiphertextBase64, backup.NonceBase64));

            return json is null ? null : FromPrivateKeyJwk(json);
        }
        catch (Exception exception) when (exception is CryptographicException or FormatException or JsonException)
        {
            return null;
        }
    }

    /// <summary>
    /// This identity's public key in the format Orbit exchanges: WebCrypto's <c>raw</c>, which is the
    /// uncompressed EC point 0x04 ‖ X ‖ Y, base64.
    /// </summary>
    public string PublicKeyBase64
    {
        get
        {
            var parameters = _keyPair.ExportParameters(includePrivateParameters: false);
            var raw = new byte[1 + (CoordinateSizeBytes * 2)];
            raw[0] = UncompressedPointMarker;
            parameters.Q.X!.CopyTo(raw, 1);
            parameters.Q.Y!.CopyTo(raw, 1 + CoordinateSizeBytes);
            return Convert.ToBase64String(raw);
        }
    }

    public EncryptedText Encrypt(string otherPartyPublicKeyBase64, string plainText)
        => Seal(AgreeKey(otherPartyPublicKeyBase64), plainText);

    /// <summary>Null when it cannot be opened - most often content sealed under a key pair since replaced.</summary>
    public string? Decrypt(string otherPartyPublicKeyBase64, EncryptedText encrypted)
    {
        try
        {
            return OpenSealed(AgreeKey(otherPartyPublicKeyBase64), encrypted);
        }
        catch (Exception exception) when (exception is CryptographicException or FormatException)
        {
            return null;
        }
    }

    /// <summary>
    /// Seals something only this user can ever open again - private notes and task lists, which have one
    /// reader rather than two. It runs the same agreement as chat with this key on both sides: no second
    /// party, and so no second key to generate, store, back up, or restore.
    /// </summary>
    public EncryptedText EncryptForSelf(string plainText) => Encrypt(PublicKeyBase64, plainText);

    public string? DecryptForSelf(EncryptedText encrypted) => Decrypt(PublicKeyBase64, encrypted);

    /// <summary>
    /// Exports the private key and seals it under the account password, so the server can hold a backup
    /// it can never read. This is how a fresh phone gets an existing chat identity at all.
    /// </summary>
    public WrappedPrivateKeyDto WrapWithPassword(string password)
    {
        var jwk = JsonWebKey.FromPrivateKey(_keyPair.ExportParameters(includePrivateParameters: true));
        var salt = RandomNumberGenerator.GetBytes(16);
        var sealedKey = Seal(DeriveWrappingKey(password, salt, Pbkdf2IterationCount), JsonSerializer.Serialize(jwk));

        return new WrappedPrivateKeyDto(
            sealedKey.CiphertextBase64, sealedKey.NonceBase64, Convert.ToBase64String(salt), Pbkdf2IterationCount);
    }

    /// <summary>
    /// The raw ECDH shared secret, used as the AES key with nothing applied to it. See the class remarks
    /// for why this specific overload, and only this one.
    /// </summary>
    private byte[] AgreeKey(string otherPartyPublicKeyBase64)
    {
        using var otherParty = ECDiffieHellman.Create(ReadRawPublicKey(otherPartyPublicKeyBase64));
        return _keyPair.DeriveRawSecretAgreement(otherParty.PublicKey);
    }

    private static ECParameters ReadRawPublicKey(string publicKeyBase64)
    {
        var raw = Convert.FromBase64String(publicKeyBase64);
        if (raw.Length != 1 + (CoordinateSizeBytes * 2) || raw[0] != UncompressedPointMarker)
        {
            throw new CryptographicException("Expected an uncompressed P-256 public key of 65 bytes.");
        }

        return new ECParameters
        {
            Curve = ECCurve.NamedCurves.nistP256,
            Q = new ECPoint
            {
                X = raw[1..(1 + CoordinateSizeBytes)],
                Y = raw[(1 + CoordinateSizeBytes)..]
            }
        };
    }

    private static EncryptedText Seal(byte[] key, string plainText)
    {
        var plainBytes = Encoding.UTF8.GetBytes(plainText);
        var nonce = RandomNumberGenerator.GetBytes(NonceSizeBytes);
        var ciphertext = new byte[plainBytes.Length];
        var tag = new byte[TagSizeBytes];

        using var cipher = new AesGcm(key, TagSizeBytes);
        cipher.Encrypt(nonce, plainBytes, ciphertext, tag);

        // Appended rather than sent separately, because that is what the browser expects to receive.
        return new EncryptedText(
            Convert.ToBase64String([.. ciphertext, .. tag]), Convert.ToBase64String(nonce));
    }

    private static string? OpenSealed(byte[] key, EncryptedText encrypted)
    {
        var combined = Convert.FromBase64String(encrypted.CiphertextBase64);
        if (combined.Length < TagSizeBytes)
        {
            return null;
        }

        var nonce = Convert.FromBase64String(encrypted.NonceBase64);
        var ciphertext = combined[..^TagSizeBytes];
        var tag = combined[^TagSizeBytes..];
        var plainBytes = new byte[ciphertext.Length];

        using var cipher = new AesGcm(key, TagSizeBytes);
        cipher.Decrypt(nonce, ciphertext, tag, plainBytes);
        return Encoding.UTF8.GetString(plainBytes);
    }

    private static byte[] DeriveWrappingKey(string password, byte[] salt, int iterations)
        => Rfc2898DeriveBytes.Pbkdf2(
            Encoding.UTF8.GetBytes(password), salt, iterations, HashAlgorithmName.SHA256, outputLength: 32);

    public void Dispose() => _keyPair.Dispose();
}
